Delimit and quote everything.

diff --git a/make-gcc-without-xcode b/make-gcc-without-xcode
--- a/make-gcc-without-xcode
+++ b/make-gcc-without-xcode
@@ -9,34 +9,34 @@
 # Amend path for PlistBuddy.
 path+=( /usr/libexec/ )
 
-script_name="$0:t"
-script_version='1.0.0'
+script_name="${0:t}"
+script_version='1.0.1'
 xcode_installer='/Applications/Install Xcode.app'
 xcode_installer_plist="${xcode_installer}/Contents/Info.plist"
 xcode_installer_packages="${xcode_installer}/Contents/Resources/Packages"
 
 # Don't cd to ~ if no argument is given.
 function cd() {
-    if (( $# == 0 )); then
+    if (( ${#} == 0 )); then
         return 1;
     else
-        builtin cd "$@"
+        builtin cd "${@}"
     fi
 }
 
 # Writes to standard error.
 function error() {
-    echo "$script_name: $@" >&2
+    echo "${script_name}: ${@}" >&2
 }
 
 # Writes to standard output.
 function info() {
-    echo "$@" >&1
+    echo "${@}" >&1
 }
 
 # Writes version information to standard errror.
 function version() {
-    echo -e "$script_name $script_version
+    echo -e "${script_name} ${script_version}
 
 Copyright (c) 2011 Sorin Ionescu
 
@@ -46,7 +46,7 @@ under the terms of the MIT License." >&2
 
 # Writes help to standard error.
 function help() {
-    echo -e "Usage: $script_name [‐option ...]
+    echo -e "Usage: ${script_name} [‐option ...]
 
 Options:
     -v, --version          Display version and copyright.
@@ -56,8 +56,8 @@ Report bugs to <sorin.ionescu@gmail.com>." >&2
 }
 
 # Parse switches.
-while [[ "$1" == -* ]]; do
-    case "$1" in
+while [[ "${1}" == -* ]]; do
+    case "${1}" in
         ( -v | --version )
             version
             exit 0
@@ -71,7 +71,7 @@ while [[ "$1" == -* ]]; do
             break
         ;;
         ( -* )
-            error "invalid option: $1"
+            error "invalid option: ${1}"
             help
             exit 1
         ;;
@@ -79,20 +79,20 @@ while [[ "$1" == -* ]]; do
 done
 
 # Root is required to preserve permissions.
-if (( EUID != 0 )); then
-    error "$script_name requires root privileges. Running sudo..."
-    exec sudo "$0" $@
-    exit $?
+if (( ${EUID} != 0 )); then
+    error "${script_name} requires root privileges. Running sudo..."
+    exec sudo "${0}" "${@}"
+    exit "${?}"
 fi
 
 # Make sure the xcode_installer is not missing before continuing.
-if [[ ! -d "$xcode_installer" ]]; then
+if [[ ! -d "${xcode_installer}" ]]; then
     error "'${xcode_installer}' not found."
     exit 1
 fi
 
-xcode_version="$( PlistBuddy -c 'Print :CFBundleShortVersionString' "$xcode_installer_plist" )"
-mac_osx_version="$( PlistBuddy -c 'Print :LSMinimumSystemVersion' "$xcode_installer_plist" )"
+xcode_version="$( PlistBuddy -c 'Print :CFBundleShortVersionString' "${xcode_installer_plist}" )"
+mac_osx_version="$( PlistBuddy -c 'Print :LSMinimumSystemVersion' "${xcode_installer_plist}" )"
 archive_prefix="${PWD}/${script_name#make-}-${xcode_version}-mac-os-x-${mac_osx_version}"
 
 packages=(
@@ -115,7 +115,7 @@ packages=(
 )
 
 # Make sure packages are not missing before continuing.
-for package in $packages; do
+for package in "${packages[@]}"; do
     if [[ ! -e "${xcode_installer_packages}/${package}" ]]; then
         error "Package '${package}' is missing. Xcode Installer is corrupt."
         exit 1
@@ -140,43 +140,43 @@ usr/share/man/man1/xcode-select.1
 usr/share/xcode-select
 '
 
-payload_file_dir=$( mktemp -d -t "$script_name" )
-payload_data_dir=$( mktemp -d -t "$script_name" )
-package_merge_dir=$( mktemp -d -t "$script_name" )
+payload_file_dir="$( mktemp -d -t "${script_name}" )"
+payload_data_dir="$( mktemp -d -t "${script_name}" )"
+package_merge_dir="$( mktemp -d -t "${script_name}" )"
 
 info "Extracting:"
-for package in $packages; do
-    info "  $package"
+for package in "${packages[@]}"; do
+    info "  ${package}"
 
     # Set full path to package.
     package_path="${xcode_installer_packages}/${package}"
 
     # Extract Payload file from package.
-    ( cd "$payload_file_dir" && xar -x -f "$package_path" Payload )
+    ( cd "${payload_file_dir}" && xar -x -f "${package_path}" Payload )
 
-    # ZSH does not support array of arrays; fake it.
-    included_files=( ${(ps:\n:)package_includes[$package]} )
-    excluded_files=( ${(ps:\n:)package_excludes[$package]} )
+    # Zsh does not support array of arrays; fake it.
+    included_files=( "${(ps:\n:)package_includes[${package}]}" )
+    excluded_files=( "${(ps:\n:)package_excludes[${package}]}" )
 
     # Prepend the -f cpio switch to each item.
     index=1
-    length=$(( $#excluded_files * 2 ))
-    while (( $index <= $length )); do
-        excluded_files[$index]=( '-f' "$excluded_files[$index]" )
+    length=$(( ${#excluded_files} * 2 ))
+    while (( ${index} <= ${length} )); do
+        excluded_files[${index}]=( '-f' "${excluded_files[${index}]}" )
         (( index += 2 ))
     done
 
     # Extract Payload file.
-    ( cd "$payload_data_dir" \
+    ( cd "${payload_data_dir}" \
           && gzcat < "${payload_file_dir}/Payload" \
-          | cpio -idm $excluded_files $included_files 2>/dev/null )
+          | cpio -idm ${excluded_files} ${included_files} 2>/dev/null )
 
     # Merge package files.
-    ditto "${payload_data_dir}${package_root[$package]}" "$package_merge_dir"
+    ditto "${payload_data_dir}${package_root[${package}]}" "${package_merge_dir}"
 
     # Clean directories for next package.
-    for dirty_dir in "$payload_file_dir" "$payload_data_dir"; do
-        ( cd "$dirty_dir" && find . -path './*' -maxdepth 1 -exec rm -rf '{}' \; )
+    for dirty_dir in "${payload_file_dir}" "${payload_data_dir}"; do
+        ( cd "${dirty_dir}" && find . -path './*' -maxdepth 1 -exec rm -rf '{}' \; )
     done
 done
 
@@ -186,16 +186,16 @@ info '  Dummy Xcode Files'
 xcodebuild_file="${package_merge_dir}/usr/bin/xcodebuild"
 cat <<-END
 #!/bin/sh
-Xcode $xcode_version
-END >! $xcodebuild_file
-chmod 755 $xcodebuild_file
+Xcode ${xcode_version}
+END > "${xcodebuild_file}"
+chmod 755 "${xcodebuild_file}"
 
 # Do not overwrite existing files.
 info 'Purging:'
 info '  Existing Files'
-( cd "$package_merge_dir" || exit
+( cd "${package_merge_dir}" || exit
   # Find all files and replace './' with '/'.
-  for existing_file in $(find . ! -type d | sed -e 's:^\.::g'); do
+  for existing_file in "$(find . ! -type d | sed -e 's:^\.::g')"; do
       if [[ -e "${existing_file}" ]] || [[ -L "${existing_file}" ]]; then
           # Delete all existing files (replace '/' with './').
           rm -f ".${existing_file}"
@@ -210,7 +210,7 @@ if [[ -f "${package_merge_dir}/usr/share/xcode-select/xcode_dir_path" ]]; then
 fi
 
 # Use high compression.
-if (( $+commands[xz] )); then
+if (( ${+commands[xz]} )); then
     archive="${archive_prefix}.cpio.xz"
     compressor='xz'
 else
@@ -219,27 +219,27 @@ else
 fi
 
 info "Archiving:"
-info "  $archive"
+info "  ${archive}"
 
 # Do not archive the directory, only the contents,
 # or risk having tar change / permissions,
 # and crash the system until fixed.
-( cd "$package_merge_dir" \
+( cd "${package_merge_dir}" \
     && ls -1A \
     | xargs -I% find '%' -depth -print0 \
-    | cpio -0o 2>/dev/null \
-    | "$compressor" -9 > "$archive" )
+    | cpio -0o 2> /dev/null \
+    | "${compressor}" -9 > "${archive}" )
 
 info 'Purging:'
 info '  Temporary Files'
-rm -rf "$payload_file_dir" "$payload_data_dir" "$package_merge_dir"
+rm -rf "${payload_file_dir}" "${payload_data_dir}" "${package_merge_dir}"
 
-if [[ "$archive" == *.xz ]]; then
+if [[ "${archive}" == *.xz ]]; then
     decompressor='xzcat'
 else
     decompressor='gzcat'
 fi
 
 info 'Install:'
-info "  cd / && "$decompressor" < '$archive' | sudo cpio -idmv"
+info "  cd / && "${decompressor}" < '${archive}' | sudo cpio -idmv"
 
diff --git a/uninstall-gcc-without-xcode b/uninstall-gcc-without-xcode
--- a/uninstall-gcc-without-xcode
+++ b/uninstall-gcc-without-xcode
@@ -5,23 +5,23 @@
 #        AUTHOR:  Sorin Ionescu <sorin.ionescu@gmail.com>
 # ------------------------------------------------------------------------------
 
-script_name="$0:t"
-script_version='1.0.0'
-cached_argv="$argv"
+script_name="${0:t}"
+script_version='1.0.1'
+cached_argv="${argv}"
 
 # Writes to standard error.
 function error() {
-    echo "$script_name: $@" >&2
+    echo "${script_name}: ${@}" >&2
 }
 
 # Writes to standard output.
 function info() {
-    echo "$@" >&1
+    echo "${@}" >&1
 }
 
 # Writes version information to standard errror.
 function version() {
-    echo -e "$script_name $script_version
+    echo -e "${script_name} ${script_version}
 
 Copyright (c) 2011 Sorin Ionescu
 
@@ -31,7 +31,7 @@ under the terms of the MIT License." >&2
 
 # Writes help to standard error.
 function help() {
-    echo -e "Usage: $script_name [‐option ...] archive [directory]
+    echo -e "Usage: ${script_name} [‐option ...] archive [directory]
 
 Options:
     -v, --version          Display version and copyright.
@@ -41,8 +41,8 @@ Report bugs to <sorin.ionescu@gmail.com>." >&2
 }
 
 # Parse switches.
-while [[ "$1" == -* ]]; do
-    case "$1" in
+while [[ "${1}" == -* ]]; do
+    case "${1}" in
         ( -v | --version )
             version
             exit 0
@@ -56,7 +56,7 @@ while [[ "$1" == -* ]]; do
             break
         ;;
         ( -* )
-            error "invalid option: $1"
+            error "invalid option: ${1}"
             help
             exit 0
         ;;
@@ -64,20 +64,20 @@ while [[ "$1" == -* ]]; do
 done
 
 # Get archive.
-if (( $# < 1 )); then
+if (( ${#} < 1 )); then
     error "No archive given."
     help
     exit 1
 else
-    if [[ ! -e "$1" ]]; then
-        error "Archive '$1' does not exist."
+    if [[ ! -e "${1}" ]]; then
+        error "Archive '${1}' does not exist."
         help
         exit 1
     else
-        archive="$(cd "$1:h" && pwd)/$1:t"
-        if [[ "$archive" == *.xz ]]; then
-            if (( ! $+commands[xzcat] )); then
-                error "Cannot extract '$archive' because XZ Utils are not installed."
+        archive="$(cd "${1:h}" && pwd)/${1:t}"
+        if [[ "${archive}" == *.xz ]]; then
+            if (( ! ${+commands[xzcat]} )); then
+                error "Cannot extract '${archive}' because XZ Utils are not installed."
                 exit 1
             else
                 decompressor='xzcat'
@@ -90,59 +90,59 @@ else
 fi
 
 # Get directory.
-if (( $# < 1 )); then
+if (( ${#} < 1 )); then
     error "No directory given, assuming /."
     directory='/'
 else
-    if [[ ! -e "$1" ]]; then
-        error "Directory '$1' does not exist."
+    if [[ ! -e "${1}" ]]; then
+        error "Directory '${1}' does not exist."
         help
         exit 1
     else
-        directory="$1"
+        directory="${1}"
         shift
     fi
 fi
 
 # Root is required to uninstall.
-if [[ ! -w "$directory" ]]; then
-    error "$script_name requires root privileges. Running sudo..."
-    exec sudo "$0" $cached_argv
-    exit $?
+if [[ ! -w "${directory}" ]]; then
+    error "${script_name} requires root privileges. Running sudo..."
+    exec sudo "${0}" "${cached_argv[@]}"
+    exit ${?}
 fi
 
 # Directories will be deleted last.
 directories="$(mktemp -t uninstall-gcc-without-xcode.directories)"
 
 # Change CWD to installation directory.
-cd "$directory"
+cd "${directory}"
 
 info 'Purging:'
 info '  Files'
 while read item; do
-    if [[ -L "$item" ]]; then
-        unlink $item""
-    elif [[ -f "$item" ]]; then
-        rm -f "$item"
+    if [[ -L "${item}" ]]; then
+        unlink "${item}"
+    elif [[ -f "${item}" ]]; then
+        rm -f "${item}"
     else
-        if [[ -d "$item" ]]; then
-            echo "$item" >> $directories
+        if [[ -d "${item}" ]]; then
+            echo "${item}" >> "${directories}"
         fi
     fi
-done < <( "$decompressor" < "$archive" | cpio -it 2>/dev/null | sed -e 's:/*$::g' )
+done < <( "${decompressor}" < "${archive}" | cpio -it 2> /dev/null | sed -e 's:/*$::g' )
 
 info '  Directories'
 while read item; do
     ds_store="${item}/.DS_Store"
-    if [[ -f "$ds_store" ]]; then
-        rm -f "$ds_store"
+    if [[ -f "${ds_store}" ]]; then
+        rm -f "${ds_store}"
     fi
 
-    if [[ -n "$(find "$item" -type d -maxdepth 0 -empty 2>/dev/null)" ]]; then
-       rmdir $item
+    if [[ -n "$(find "${item}" -type d -maxdepth 0 -empty 2> /dev/null)" ]]; then
+       rmdir "${item}"
     fi
-done < $directories
+done < "${directories}"
 
 info '  Temporary Files'
-rm $directories
+rm "${directories}"
 
